// OG Forge - LemonSqueezy Webhook Handler

export const config = {
  runtime: 'edge',
};

export default async function handler(req) {
  try {
    const body = await req.text();
    const signature = req.headers.get('x-signature') || '';

    // Verify webhook signature (in production, verify with LemonSqueezy secret)
    // const secret = process.env.LEMON_SQUEEZY_SECRET;
    // const hmac = crypto.createHmac('sha256', secret);
    // const digest = hmac.update(body).digest('hex');

    const event = JSON.parse(body);
    const eventName = event.meta?.event_name || event.event_name;

    console.log(`[WEBHOOK] Received event: ${eventName}`);

    switch (eventName) {
      case 'subscription_created':
      case 'subscription_updated':
        console.log('[WEBHOOK] Subscription event:', event.data?.attributes?.status);
        break;

      case 'order_created':
      case 'payment_succeeded':
        console.log('[WEBHOOK] Order created/payment succeeded');
        // License key already generated by LemonSqueezy
        break;

      case 'subscription_cancelled':
      case 'subscription_expired':
        console.log('[WEBHOOK] Subscription ended');
        break;

      case 'test':
        console.log('[WEBHOOK] Test webhook received');
        break;

      default:
        console.log(`[WEBHOOK] Unknown event: ${eventName}`);
    }

    return new Response(JSON.stringify({
      received: true,
      event: eventName
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('[WEBHOOK] Error:', error.message);
    return new Response(JSON.stringify({
      error: error.message || 'Webhook processing failed'
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}